version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=carryontech
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '8080:80'
      - '443:443'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mysql

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-latest
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.18.0.1

    # bitrix24:
  #   image: lookinio/bitrix:latest
  #   container_name: bitrix24
  #   ports:
  #     - "8888:80"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpass
  #   volumes:
  #     - bitrix_data:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - network-zabbix
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - zabbix-frontend
      - go-app1
      - go-app2
      - go-app3

  go-app1:
    build: ./go-hello1
    networks:
      - network-zabbix
    ports:
      - "9001:8080"

  go-app2:
    build: ./go-hello2
    networks:
      - network-zabbix
    ports:
      - "9002:8080"

  go-app3:
    build: ./go-hello3
    networks:
      - network-zabbix
    ports:
      - "9003:8080"

networks:
  network-zabbix:
    driver: bridge