version: '3.1'

networks:
  network-zabbix:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/data'
    environment:
      - MYSQL_ROOT_PASSWORD=carryontech
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mysql
   
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
    depends_on:
      - mysql
      - zabbix-server
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.0.1
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.18.0.1

  go-app1:
    build: ./go-hello1
    networks:
      - network-zabbix
    ports:
      - "9001:8080"

  go-app2:
    build: ./go-hello2
    networks:
      - network-zabbix
    ports:
      - "9002:8080"

  go-app3:
    build: ./go-hello3
    networks:
      - network-zabbix
    ports:
      - "9003:8080"

  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - network-zabbix
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - zabbix-frontend
      - grafana
      - go-app1
      - go-app2
      - go-app3
    restart: always

  # wireguard:
  #   container_name: wireguard
  #   image: linuxserver/wireguard
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Sao_Paulo
  #     - SERVERURL=213.171.25.166
  #     - SERVERPORT=51820
  #     - PEERS=client1
  #     - PEERDNS=8.8.8.8
  #     - PEERDNS=auto
  #     - INTERNAL_SUBNET=10.13.13.0
  #   volumes:
  #     - ./wireguard/config:/config
  #     - /lib/modules:/lib/modules
  #   ports:
  #     - "51820:51820/udp"
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   restart: unless-stopped
  #   networks:
  #     - network-zabbix

  freeipa:
      container_name: freeipa
      image: freeipa/freeipa-server:rocky-8
      networks:
        network-zabbix:
          ipv4_address: 172.20.0.10
      hostname: ipa.example.local
      domainname: example.local
      restart: unless-stopped
      tty: true
      stdin_open: true
      privileged: true  # Required for systemd to manage cgroups
      ports:
        - "10080:80"    # HTTP
        - "10443:443"   # HTTPS
        - "389:389"     # LDAP
        - "636:636"     # LDAPS
        - "88:88"       # Kerberos TCP
        - "464:464"     # Kerberos TCP
        - "88:88/udp"   # Kerberos UDP
        - "464:464/udp" # Kerberos UDP
        - "123:123/udp" # NTP
        - "53:53/udp"   # DNS
        - "53:53/tcp"   # DNS
      environment:
        - IPA_SERVER_HOSTNAME=ipa.example.local
        - IPA_SERVER_IP=172.20.0.10
        - TZ=America/Sao_Paulo
      command:
        - ipa-server-install
        - -U
        - --domain=example.local
        - --realm=EXAMPLE.LOCAL
        - --ds-password=YourStrongPassword123
        - --admin-password=YourStrongPassword123
        - --no-host-dns
        - --unattended
        - --setup-dns
        - --auto-forwarders
        - --no-dnssec-validation
      volumes:
        - ./freeipa/data:/data:rw
        - ./freeipa/logs:/var/log:rw
        - /sys/fs/cgroup:/sys/fs/cgroup:rw  # Writable cgroup mount for systemd
      cap_add:
        - SYS_ADMIN  # Required for cgroup management
        - SYS_TIME
        - NET_ADMIN
      security_opt:
        - seccomp:unconfined
      tmpfs:
        - /run
        - /tmp
        - /run/lock  # Required for systemd