@startuml
skinparam defaultTextAlignment center
skinparam linetype ortho

node "Центр обработки данных" as OnPrem {
  node "Сетевое оборудование" as NetwoekEquipment {
    node "Коммутатор" as Switch
    node "Маршрутизатор" as Router
  }

  node "Вычислительный кластер" as Server {
    node "Узел 1" as Node1
    node "Узел 2" as Node2
  }

  storage "Система хранения данных" as DSS {
      database "Базы данных с \n чувствительной информацией" as localSensetiveDB
      database "Базы данных сервисов" as localDB
  }
}

cloud "WAN" as WAN 


DSS -Up--> Server : " "
Server -Up--> NetwoekEquipment : " "
NetwoekEquipment -Up--> WAN : "Выход в WAN"