version: '3'
services:
  ansible:
    build: ./ansible
    volumes:
      - ./go-app:/go/code
    networks:
      - app-network
    depends_on:
      - alpine
    command: ["sh", "-c", "while true; do sleep 3600; done"]

  alpine:
    build: ./alpine
    networks:
      - app-network
    hostname: alpine

networks:
  app-network:
    driver: bridge