FROM alpine:latest

RUN apk add --no-cache openssh go bash \
    && id -u ansible || adduser -D ansible \
    && mkdir -p /home/ansible/.ssh \
    && chown -R ansible:ansible /home/ansible/.ssh \
    && ssh-keygen -A \
    && echo -e "Port 22\nPermitRootLogin no\nPasswordAuthentication no\nPubkeyAuthentication yes\nChallengeResponseAuthentication no" > /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]