FROM alpine:latest

RUN apk add --no-cache python3 py3-pip openssh-client sshpass bash \
    && pip3 install --break-system-packages ansible \
    && adduser -D ansible \
    && mkdir -p /home/ansible/.ssh \
    && chown -R ansible:ansible /home/ansible/.ssh \
    && chmod 700 /home/ansible/.ssh

WORKDIR /ansible