FROM alpine:latest

RUN apk add --no-cache python3 py3-pip openssh-client sshpass bash \
    && pip3 install --break-system-packages ansible \
    && mkdir -p /root/.ssh \
    && chmod 700 /root/.ssh

WORKDIR /ansible