FROM alpine:latest

RUN apk add --no-cache openssh go bash \
    && id -u ansible || adduser -D ansible \
    && mkdir -p /home/ansible/.ssh \
    && chown -R ansible:ansible /home/ansible/.ssh \
    && ssh-keygen -A \
    && printf "PermitRootLogin no\nPasswordAuthentication no\nPubkeyAuthentication yes\n" >> /etc/ssh/sshd_config


EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]