FROM alpine:latest

RUN apk add --no-cache openssh go bash \
    && id -u ansible || adduser -D ansible \
    && mkdir -p /home/ansible/.ssh \
    && chown -R ansible:ansible /home/ansible/.ssh \
    && ssh-keygen -A \
    && printf '%s\n' \
       'Port 22' \
       'PermitRootLogin no' \
       'PasswordAuthentication no' \
       'PubkeyAuthentication yes' \
       'ChallengeResponseAuthentication no' \
       >> /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]