version: '3.8'

services:
  alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: alpine_target
    command: ["sh", "-c", "while true; do sleep 30; done"]
    networks:
      - ansible_net
    expose:
      - "22"

  ansible:
    build:
      context: .
      dockerfile: Dockerfile.ansible
    container_name: ansible_controller
    volumes:
      - ./ansible:/ansible
      - ./go-app:/go-app
      - ~/.ssh/id_rsa.pub:/home/ansible/.ssh/id_rsa.pub:ro
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
    working_dir: /ansible
    networks:
      - ansible_net
    depends_on:
      - alpine
    tty: true
    stdin_open: true
    command: ["sh", "-c", "while true; do sleep 3600; done"]

networks:
  ansible_net:
    driver: bridge
